services:
  hub:
    build:
      context: .
      dockerfile: dockerfile
    image: jhub-marimo:latest
    container_name: jupyterhub-marimo
    restart: unless-stopped
    ports:
      - "8000:8000"  # JupyterHub port
      - "9000:9000"  # FastAPI port
    volumes:
      - jupyterhub-data:/home
      - ./logs:/var/log/jupyterhub
      - ./api:/srv/jupyterhub/api
    env_file:
      - .env

    networks:
      - jupyter-network

volumes:
  jupyterhub-data:
    driver: local

networks:
  jupyter-network:
    driver: bridge